# Generated by Django 4.1 on 2023-04-27 06:34

from django.db import migrations, models
import django.db.models.deletion
import sloth.core.base
import sloth.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0004_situacaoauditoria_alter_itemchecklist_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prazo_final', models.DateField(verbose_name='Prazo Final')),
                ('auditoria', sloth.db.models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auditoria.auditoria', verbose_name='Auditoria')),
                ('checklist', sloth.db.models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auditoria.checklist', verbose_name='Checklist')),
                ('responsavel', sloth.db.models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auditoria.auditor', verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Checklist',
                'verbose_name_plural': 'Checklist',
            },
            bases=(models.Model, sloth.core.base.ModelMixin),
        ),
    ]
