# Generated by Django 4.1 on 2023-04-27 06:47

from django.db import migrations, models
import django.db.models.deletion
import sloth.core.base
import sloth.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0005_checklistauditoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', sloth.db.models.CharField(max_length=255, verbose_name='Nome')),
                ('arquivo', models.FileField(upload_to='anexos', verbose_name='Arquivo')),
            ],
            options={
                'verbose_name': 'Anexo',
                'verbose_name_plural': 'Anexos',
            },
            bases=(models.Model, sloth.core.base.ModelMixin),
        ),
        migrations.CreateModel(
            name='Parecer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', sloth.db.models.CharField(max_length=255, verbose_name='Nome')),
                ('cor', sloth.db.models.ColorField(max_length=7, verbose_name='Cor')),
            ],
            options={
                'verbose_name': 'Parecer',
                'verbose_name_plural': 'Pareceres',
            },
            bases=(models.Model, sloth.core.base.ModelMixin),
        ),
        migrations.CreateModel(
            name='ItemAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidencias', sloth.db.models.TextField(blank=True, null=True, verbose_name='Evidências')),
                ('anexos', sloth.db.models.OneToManyField(to='auditoria.anexo', verbose_name='Anexos')),
                ('checklist_auditoria', sloth.db.models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auditoria.checklistauditoria', verbose_name='Checklist')),
                ('item', sloth.db.models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auditoria.itemchecklist', verbose_name='Item')),
                ('parecer', sloth.db.models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auditoria.parecer')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Itens',
            },
            bases=(models.Model, sloth.core.base.ModelMixin),
        ),
    ]
