# Generated by Django 4.1 on 2023-04-27 09:27

from django.db import migrations
import django.db.models.deletion
import sloth.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0006_anexo_parecer_itemauditoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemauditoria',
            options={'verbose_name': 'Quesito', 'verbose_name_plural': 'Quesitos'},
        ),
        migrations.AlterField(
            model_name='itemauditoria',
            name='item',
            field=sloth.db.models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auditoria.itemchecklist', verbose_name='Enunciado'),
        ),
    ]
